server:
  port: ${PORT:3002}
  address: 0.0.0.0
  servlet:
    context-path: /bank-api

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: "never"
